title: Cuba Weather Red Cuba Python
description: Application programming interface of the Cuba Weather project for redcuba.cu implemented in Python
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
